name: Deploy Frontend
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build || true  # No build step needed for Express
      - uses: azure/webapps-deploy@v3
        with:
          app-name: ZUniques-Hackathon-STG-UAEN-02
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: .
